/* AUTOMATICALLY GENERATED */
#ifndef __LOWFAT_CONFIG_H
#define __LOWFAT_CONFIG_H

#define _LOWFAT_SIZES ((size_t *)0x200000)
#define _LOWFAT_MAGICS ((uint64_t *)0x300000)
#define _LOWFAT_REGION_SIZE 34359738368ull

#define LOWFAT_REVERSE_MEM_LAYOUT 1

#endif	/* __LOWFAT_CONFIG_H */
